### ISSUE TITLE
" issueベースの開発"のレビュー依頼

### ISSUE THREAD

**Issue by riva773** [riva773/comedy_app#26]
# 事前準備
- [ ] インフラ環境構築
- [ ] Docker環境構築

# 実装予定の機能

- [ ] 投稿機能 
- [ ] ログイン機能
- [ ] いいね機能
- [ ] フォロー機能
- [ ] ジャンル検索機能
- [ ] レコメンド機能
- [ ] タグ機能 
- [ ] チャット機能
- [ ] ランキング機能 
- [ ] 趣味嗜好一覧機能 
- [ ] ニュース取得機能
- [ ] お笑いチャレンジ機能
- [ ] コミュニティ機能

# 必要な画面
- [ ] ログイン前トップページ
- [ ] ログイン後トップページ
- [ ] ログイン画面
- [ ] メールアドレス変更画面
- [ ] パスワード変更画面
- [ ] ユーザー登録画面
- [ ] ランキング画面
- [ ] 設定画面
- [ ] 投稿詳細画面
- [ ] フォロー、フォロワー一覧画面
- [ ] プロフィール画面
- [ ] いいね一覧画面
- [ ] DM画面
- [ ] ニュース一覧画面
- [ ] ニュース詳細画面
- [ ] コミュニティ一覧画面
- [ ] コミュニティ詳細画面
- [ ] チャレンジ画面

**Comment by tmtkzk0823** [comment]
ご提出ありがとうございます。
以下コメントになります。

---

- デプロイ、rails newなどのカードも作成しましょう。

・外部APIや技術に関して調査するものがあれば、それもカードを用意しましょう。

また、ストーリーポイント5を付けているカードですが、初めて取り組むものや見通しが立っていないものにポイント5を付けているように見受けられました。ストーリーポイント1,2になるまで細分化することで、分かっている箇所、不透明な箇所が可視化されますし、進捗を感じながら開発を進めることができます。

上記の観点も踏まえて再度、ご確認をお願いします。

**Comment by riva773** [comment]
ご確認ありがとうございます。
いただいたフィードバックをもとにissueをより細分化して、作成しました。
抽象的なissueの解像度が上がったかと思います。

再度ご確認をお願いいたします。

**Comment by tmtkzk0823** [comment]
修正ありがとうございます。
概ね良さそうです。
LGTMです！
